# Generated by Django 5.0.7 on 2025-10-03 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('staff', 'Staff'), ('owner', 'Owner'), ('superadmin', 'Super Admin')], default='customer', max_length=20),
        ),
    ]
